version: '3.7'

services:

    php:
        build: php
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        restart: always

    server:
        build: ./server
        ports:
            - 80:80
            - 443:443
        working_dir: ${APP_PATH_CONTAINER}
        restart: always
        environment:
            - NGINX_HOST=localhost
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - ${LETSENCRYPT_PATH_HOST}:${LETSENCRYPT_PATH_CONTAINER}
            - ${NGINX_CONF_HOST}:${NGINX_CONF_CONTAINER}
            - ${LOG_PATH_HOST}:${LOG_PATH_CONTAINER}
        depends_on:
            - php
        links:
            - php

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
        volumes: 
            - ${DB_PATH_HOST}:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 6081:8080

    composer:
        image: composer
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: bash -c "composer install && tail -f /dev/null"
        # command: bash -c "tail -f /dev/null"